apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: backend-api
        env:
        - name: SITE_NAME
          valueFrom:
            configMapKeyRef:
              name: e101-config-map
              key: SITE_NAME
        - name: TURBINE_NAME
          valueFrom:
            configMapKeyRef:
              name: e101-config-map
              key: TURBINE_NAME
        - name: TURBINE_INFO
          valueFrom:
            configMapKeyRef:
              name: e101-config-map
              key: TURBINE_INFO