apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: backend-api-kustomization
  namespace: default
resources:
  - ../../../../base/wt-monitoring-app
  - e101-config-map.yaml
patches:
  - path: e101-config.yaml

