apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: backend-api-customization
  namespace: default
resources:
  - ../../../../base/wt-monitoring-app
  - e101-config-map.yaml
patchesStrategicMerge:
  - e101-config.yaml

