apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: w102-backend-api-kustomization
  namespace: default
resources:
  - ../../../../base/wt-monitoring-app
  - w102-config-map.yaml
patches:
  - path: w102-config.yaml

