apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: wt-app-base
  namespace: default
resources:
  - frontend-ui-deployment.yaml
  - data-processor-deployment.yaml
  - influxdb-deployment.yaml
  - opcua-server-deployment.yaml
  - rabbitmq-deployment.yaml
  - sensor-simulator-deployment.yaml
  - backend-api-deployment.yaml

