apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: w101-backend-api-kustomization
  namespace: default
resources:
  - ../../../../base/wt-monitoring-app
  - w101-config-map.yaml
patches:
  - path: w101-config.yaml

